CREATE DATABASE HospitalManagementSystem; -- DATABASE
GO
USE HospitalManagementSystem;
GO
/*SCHEMA'S*/
CREATE SCHEMA [SECURITY];
GO

CREATE SCHEMA HOSPITAL;
GO


/* TABLES */

-- SECURITY SECTION --
CREATE TABLE [SECURITY].ROL(
	Id					INT NOT NULL IDENTITY (1,1),
	Rol					VARCHAR (50) NOT NULL
);
GO
CREATE TABLE [SECURITY].[STATUS](
	Id					INT NOT NULL IDENTITY (1,1),
	Status				VARCHAR (50) NOT NULL
);
GO
CREATE TABLE [SECURITY].[USER](
	Id					INT NOT NULL,					--FOREIGN KEY (EMPLOYEE)
	Rol					INT NOT NULL,					--FOREIGN KEY
	Status				INT NOT NULL,					--FOREIGN KEY
	Email				VARCHAR (50) NOT NULL,
	Password			VARCHAR (MAX) NOT NULL
);
GO

-- HOSPITAL SECTION ---
CREATE TABLE HOSPITAL.JOB(
	Id					INT NOT NULL IDENTITY (1,1),
	Position			VARCHAR (255) NOT NULL,
	Description			VARCHAR(MAX) NULL				--IN CASE OF MEDICAL / NURSING WORK: MEDICAL SPECIALTY
);
GO
CREATE TABLE HOSPITAL.EMPLOYEE(
	Id					INT NOT NULL IDENTITY (1,1),
	Name				VARCHAR (150) NOT NULL,
	LastName			VARCHAR (50) NOT NULL,
	MotherLastName		VARCHAR (50) NOT NULL,
	Gender				CHAR (1) NOT NULL,
	BirthDate			DATE NOT NULL,
	Age					INT NULL, 						--SELF-GENERATED
	Email				VARCHAR (50) NOT NULL,
	Phone				CHAR (10) NULL,
	Address				VARCHAR (255) NOT NULL,
	Job					INT NOT NULL,					--FOREIGN KEY
	Status				INT NOT NULL					--FOREIGN KEY
);
GO
CREATE TABLE HOSPITAL.PATIENT(
	Id					INT NOT NULL IDENTITY (1,1),
	CURP				CHAR (18) NOT NULL,
	Name				VARCHAR (150) NOT NULL,
	LastName			VARCHAR (50) NOT NULL,
	MotherLastName		VARCHAR (50) NOT NULL,
	Gender				CHAR (1) NOT NULL,
	BirthDate			DATE NOT NULL,
	Age					INT NULL,	 					--SELF-GENERATED
	Phone				CHAR (10) NULL,
	Address				VARCHAR (255) NOT NULL,
	Status				INT NOT NULL					--FOREIGN KEY
);
GO
CREATE TABLE HOSPITAL.ALLOCATION(
	Id					INT NOT NULL IDENTITY (1,1),
	Patient				INT NOT NULL,					--FOREIGN KEY
	DoctorInCharge		INT NOT NULL,					--FOREIGN KEY (EMPLOYEE)
	Assgnment			VARCHAR (15) NOT NULL,
	DateOfAssignment	DATETIME NOT NULL,
	DischargeDate		DATETIME NULL
);
GO
CREATE TABLE HOSPITAL.CONSULTATION(
	Id					INT NOT NULL IDENTITY (1,1),
	Allocation			INT NOT NULL,					--FOREIGN KEY
	Patient				INT NOT NULL,					--FOREIGN KEY
	Doctor				INT NOT NULL,					--FOREIGN KEY (EMPLOYEE)
	ConsultationDate	DATETIME NOT NULL,
	Symptoms			VARCHAR (MAX) NOT NULL,
	Diagnosis			VARCHAR (MAX) NOT NULL,
	Treatment			VARCHAR (MAX) NOT NULL
);
GO


/* CONSTRAINT'S */

-- PRIMARY KEY'S --
	--SECURITY--
ALTER TABLE [SECURITY].ROL
	ADD CONSTRAINT PK_ROL_ID PRIMARY KEY (Id);
GO

ALTER TABLE [SECURITY].[STATUS]
	ADD CONSTRAINT PK_STATUS_ID PRIMARY KEY (Id);
GO

	--HOSPITAL--
ALTER TABLE HOSPITAL.JOB
	ADD CONSTRAINT PK_JOB_ID PRIMARY KEY (Id);
GO

ALTER TABLE HOSPITAL.EMPLOYEE
	ADD CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY (Id);
GO

ALTER TABLE HOSPITAL.PATIENT
	ADD CONSTRAINT PK_PATIENT_ID PRIMARY KEY (Id);
GO

ALTER TABLE HOSPITAL.ALLOCATION
	ADD CONSTRAINT PK_ALLOCATION_ID PRIMARY KEY (Id);
GO

ALTER TABLE HOSPITAL.CONSULTATION
	ADD CONSTRAINT PK_CONSULTATION_ID PRIMARY KEY (Id);
GO

-- FOREIGN KEY'S --
	--SECURITY--
ALTER TABLE [SECURITY].[USER]
	ADD 
	CONSTRAINT FK_USER_ID FOREIGN KEY (Id) REFERENCES HOSPITAL.EMPLOYEE (Id),
	CONSTRAINT FK_USER_ROL FOREIGN KEY (Rol) REFERENCES [SECURITY].ROL (Id),
	CONSTRAINT FK_USER_STATUS FOREIGN KEY (Status) REFERENCES [SECURITY].[STATUS] (Id);
GO

	--HOSPITAL--
ALTER TABLE HOSPITAL.EMPLOYEE
	ADD 
	CONSTRAINT FK_EMPLOYEE_JOB FOREIGN KEY (Job) REFERENCES HOSPITAL.JOB (Id),
	CONSTRAINT FK_EMPLOTEE_STATUS FOREIGN KEY (Status) REFERENCES [SECURITY].[STATUS] (Id);
GO

ALTER TABLE HOSPITAL.PATIENT
	ADD
	CONSTRAINT FK_PATIENT_STATUS FOREIGN KEY (Status) REFERENCES [SECURITY].[STATUS] (Id);

ALTER TABLE HOSPITAL.ALLOCATION
	ADD 
	CONSTRAINT FK_ALLOCATION_PATIENT FOREIGN KEY (Patient) REFERENCES HOSPITAL.PATIENT (Id),
	CONSTRAINT FK_ALLOCATION_DOCTORINCHARGE FOREIGN KEY (DoctorInCharge) REFERENCES HOSPITAL.EMPLOYEE (Id);
GO

ALTER TABLE HOSPITAL.CONSULTATION
	ADD 
	CONSTRAINT FK_CONSULTATION_ALLOCATION FOREIGN KEY (Allocation) REFERENCES HOSPITAL.ALLOCATION (Id),
	CONSTRAINT FK_CONSULTATION_PATIENT FOREIGN KEY (Patient) REFERENCES HOSPITAL.PATIENT (Id),
	CONSTRAINT FK_CONSULTATION_DOCTOR FOREIGN KEY (Doctor) REFERENCES HOSPITAL.EMPLOYEE (Id);
GO